# Default values for basic-app.

nameOverride: ""
fullnameOverride: ""

################
## Deployment ##
################

replicas: 1

image:
  repository: ""
  name: ""
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
#- name: azure-container-registry-credentials

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000
  # capabilities:
  #   drop:
  #   - ALL

containerPort: 8080

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

#############
## Service ##
#############

service:
  enabled: true
  type: ClusterIP
  port: 80

###################
## Configuration ##
###################

configMap:
  enabled: false
  data: {}

secret:
  enabled: false
  data: {}

#############
## Storage ##
#############

storage:
  enabled: false
  storageClassName: default
  size: 10Gi
  mountPath: /data
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
